### GET /
GET http://localhost:8080 HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
	"username": "Nick",
  	"email": "Nick123@gmail.com",
  	"password": "Nick123!",
  	"confirm_password": "Nick123!"
}

### POST /auth/login
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
  	"email": "Nick@gmail.com",
  	"password": "Nick123!"
}

### POST /uporabnik/:id
POST http://localhost:8080/users/05f72cc-285a-43b6-b434-d8d35b041265 HTTP/1.1
Content-Type: application/json

{
  	"uporabnik_id": "Nick@gmail.com",
}

### GET /uporabnik
GET http://localhost:8080/users HTTP/1.1

### GET /permissions Send Request
GET http://localhost:8080/permissions

### POST /permissions
Send Request
POST http://localhost:8080/permissions HTTP/1.1 Content-Type: application/json

{
"name": "edit_permissions"
}

### GET /roles
Send Request
GET http://localhost:8080/roles HTTP/1.1

### DELETE /roles/:id
Send Request
GET http://localhost:8080/roles/0a1966a3-c942-4d06-b65e-7b1ec HTTP/1.1

### POST /borci
POST http://localhost:8080/borci HTTP/1.1
Content-Type: application/json

{
    "ime": "Georges St-Pierre",
    "record": "26-2-0",
    "starost": "44",
    "velikost": "180",
    "teza": "83",
    "reach": "193"
}

### PATCH /roles/:id
PATCH http://localhost:8080/roles/4df92185-508a-48d3-989b-a49221dbccfa HTTp/1.1
Content-Type: application/json

{
	"name": "Admin",
	"permissions": [" 85977cff-72c8-457a-8e09-a3f488c8df55 , effc34cf-f655-4038-8fa2-38d689115db9 "]
}